name: Build MangoJuice AppImage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Update system and install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm git base-devel meson ninja libsodium libgee gettext gtk4 libadwaita vala fontconfig glib2 wget patchelf strace xorg-server-xvfb vulkan-tools
  
    - name: Build and install MangoJuice
      run: |
        meson setup build --prefix=/usr
        ninja -C build
        sudo ninja -C build install
        
    - name: Create AppImage
      working-directory: ./mangojuice/build-aux
      run: |
        chmod +x ./mangojuice-appimage.sh
        ./mangojuice-appimage.sh
        
    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v4
      with:
        name: MangoJuice-AppImage
        path: ./mangojuice/build-aux/MangoJuice-*.AppImage
